[programs.localnet]
chick_distributor = "3NHg4RvfmsqtUL9N8kryZNfdCcYqsS92BQQnmiQdEJpn"

[registry]
url = "https://anchor.projectserum.com"

#[provider]
#cluster = "localnet"
#wallet = "/home/bmstart/.config/solana/id.json"

[provider]
cluster = "devnet"
wallet = "/home/bmstart/work/solana/keys/alice.json"

[scripts]
test = "ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
